# TealeNode post-install script — run by the Inno Setup installer after file extraction.
# Downloads the model, generates config, installs and starts the Windows service.

param(
    [string]$InstallDir = "C:\Teale"
)

$ErrorActionPreference = "Stop"
$ServiceName = "TealeNode"

# --- Paths ---
$BinDir    = Join-Path $InstallDir "bin"
$ModelDir  = Join-Path $InstallDir "models"
$ConfigDir = Join-Path $InstallDir "config"
$LogDir    = Join-Path $InstallDir "logs"
$DataDir   = Join-Path $InstallDir "data"

$NssmExe    = Join-Path $BinDir "nssm.exe"
$LlamaExe   = Join-Path $BinDir "llama-server.exe"
$TealeExe   = Join-Path $BinDir "teale-node.exe"
$ConfigFile = Join-Path $ConfigDir "teale-node.toml"
$ModelUrl   = "https://huggingface.co/Qwen/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf"
$ModelFile  = Join-Path $ModelDir "Qwen3-4B-Q4_K_M.gguf"

# --- Create directories ---
foreach ($dir in @($ModelDir, $ConfigDir, $LogDir, $DataDir)) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

# --- Download model if not present ---
if (-not (Test-Path $ModelFile)) {
    Write-Host "Downloading Qwen3-4B model (about 2.5 GB)..."
    try {
        Start-BitsTransfer -Source $ModelUrl -Destination $ModelFile -Description "Downloading Qwen3-4B Q4_K_M"
    } catch {
        Write-Host "BITS unavailable, using Invoke-WebRequest..."
        Invoke-WebRequest -Uri $ModelUrl -OutFile $ModelFile -UseBasicParsing
    }
}

# --- Generate config ---
$logicalCores = (Get-CimInstance Win32_Processor | Measure-Object -Property NumberOfLogicalProcessors -Sum).Sum
$threads = [math]::Max(2, $logicalCores - 2)
$ramGB = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1073741824, 1)

$llamaPath = $LlamaExe.Replace('\', '/')
$modelPath = $ModelFile.Replace('\', '/')

$tomlContent = @"
# teale-node configuration -- auto-generated by TealeNode installer
# Machine: $env:COMPUTERNAME | RAM: $ramGB GB | Cores: $logicalCores

[relay]
url = "wss://relay.teale.com/ws"

[llama]
binary = "$llamaPath"
model = "$modelPath"
gpu_layers = 0
context_size = 8192
port = 11436
extra_args = ["--threads", "$threads"]

[node]
display_name = "$env:COMPUTERNAME"
gpu_backend = "cpu"
"@

Set-Content -Path $ConfigFile -Value $tomlContent -Encoding UTF8

# --- Stop existing service if upgrading ---
if (Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) {
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
    & $NssmExe remove $ServiceName confirm 2>$null
}

# --- Install service via NSSM ---
& $NssmExe install $ServiceName $TealeExe
& $NssmExe set $ServiceName AppParameters "--config `"$ConfigFile`""
& $NssmExe set $ServiceName AppDirectory $InstallDir
& $NssmExe set $ServiceName DisplayName "Teale Node"
& $NssmExe set $ServiceName Description "TealeNet inference supply node"

$stdoutLog = Join-Path $LogDir "teale-node-stdout.log"
$stderrLog = Join-Path $LogDir "teale-node-stderr.log"
& $NssmExe set $ServiceName AppStdout $stdoutLog
& $NssmExe set $ServiceName AppStderr $stderrLog
& $NssmExe set $ServiceName AppRotateFiles 1
& $NssmExe set $ServiceName AppRotateBytes 10485760
& $NssmExe set $ServiceName AppRestartDelay 5000
& $NssmExe set $ServiceName Start SERVICE_AUTO_START
& $NssmExe set $ServiceName AppEnvironmentExtra "APPDATA=$DataDir"

# --- Start the service ---
Start-Service -Name $ServiceName

Write-Host "TealeNode service installed and started."
